### PR TITLE
Added Myrtille

### PR DESCRIPTION
**Pull request by cedrozor**
Remote Desktop/Myrtille - [https://github.com/cedrozor/myrtille](https://github.com/cedrozor/myrtille)

A native HTML4/5 Remote Desktop Protocol client, HTTP gateway written in C# for .NET

### CODE REVIEW

**Comment by Jeffiy** [comment]
@cedrozor thanks, well done, but I'm not sure about it whether Stable, because it seems just to be created at 1 months ago.

/cc @devkhan @quozd

**Comment by cedrozor** [comment]
@Jeffiy Hi Jeffiy, Indeed, I created the repository recently but it's a very mature project I worked on for years (it was first a commercial project, you can have a look to its history into the [wiki](https://github.com/cedrozor/myrtille/wiki)). It doesn't have much comments yet because I only start to communicate on it (starting by adding it to your awesome list ^^). Thanks.

**Comment by quozd** [comment]
OK, let it be. Its more a tool than library you will rely on, so we can add it.

@cedrozor please, move the link to Tools category and I'll merge it. Thanks

**Comment by cedrozor** [comment]
@quozd Yes, it's more a tool than a library. Done it, thanks

**Comment by Jeffiy** [comment]
@cedrozor OK, thanks.

**Pull request merged**
