### PR TITLE
Add Alea GPU to new GPU category 

### PR DESCRIPTION
**Pull request by Sylwekqaz**
GPU/Alea GPU - [Alea GPU](http://www.aleagpu.com)

Provides CUDA support for all .NET languages, is fully cross platform.  **[$]**

### CODE REVIEW

**Comment by pleb** [comment]
> Actively maintained (even if that just means acknowledging open issues when they arise)

Is there a place to log tickets?

**Comment by Sylwekqaz** [comment]
I didn't find any

**Comment by pleb** [comment]
Sorry, @Sylwekqaz,

This entry isn't going to make the list for the following reason(s):

- Project is possibly not awesome

- No of response from the community suggested the previous statement is false

Don't let this setback cause you to lose heart, and we look forward to your next contribution.

Thanks, Pleb

**Comment by Jogai** [comment]
They point to stackoverflow for questions...

**Pull request closed without merging**
