### PR TITLE
nvelocity added to template engine category

### PR DESCRIPTION
**Pull request by fernandolguevara**
nvelocity added to template engine category

### CODE REVIEW

**Comment by Jeffiy** [comment]
Oops, It seems not active now.

**Comment by pleb** [comment]
Link http://nvelocity.sourceforge.net/

**Comment by pleb** [comment]
I couldn't find if the project is active. The project link is to sourceforge - I'd personally like to see sourceforge hosted projects banned given they recent behaviour.

**Comment by pleb** [comment]
I don't think the project is active

**Comment by quozd** [comment]
Closed due to inactivity

**Pull request closed without merging**
