### PR TITLE
Added a CMS

### PR DESCRIPTION
**Pull request by evilprince2009**
Previously Kentico wasn't listed under the section CMS. Added Kentico CMS to the list.

### CODE REVIEW

**Comment by pleb** [comment]
Hey @evilprince2009, seems to be a lot of change to the MD file. Was this intentional?

**Comment by evilprince2009** [comment]
> Hey @evilprince2009, seems to be a lot of change to the MD file. Was this intentional?

No ! I just added a cms under CMS section & it's basically a one liner. I changed nothing else.

**Comment by pleb** [comment]
Could be your editor, maybe?

image

**Comment by evilprince2009** [comment]
> Could be your editor, maybe?
> 
> image
> 
Maybe.

**Pull request closed without merging**
