### PR TITLE
Added Accord.NET Extensions

### PR DESCRIPTION
**Pull request by dajuric**

### CODE REVIEW

**Comment by quozd** [comment]
@dajuric please, move it to Machine Learning category, right after Accord library https://github.com/quozd/awesome-dotnet#machine-learning

**Comment by dajuric** [comment]
Moved

2015-02-17 17:44 GMT+01:00 Vitali Fokin <notifications@github.com>:

**Comment by quozd** [comment]
#66 Merged. Thank you.

Tip: you don't need to create separate pull requests for each required change, just commit to the same branch which original PR was made from.

**Comment by dajuric** [comment]
Ok,

Thank you.

2015-02-17 18:29 GMT+01:00 Vitali Fokin <notifications@github.com>:

**Pull request closed without merging**
