### PR TITLE
add Microphone

### PR DESCRIPTION
**Pull request by YaroslavSchubert**
Misc/MIcrophone- [https://github.com/rogeralsing/Microphone](https://github.com/rogeralsing/Microphone)

Microphone is a lightweight framework to run self hosting REST services using Web Api or NancyFx ontop of a Consul or ETCD cluster. Each service will start out by allocating a free port to run on, once the service is started, it will register itself in the local cluster provider.

### CODE REVIEW

**Comment by devkhan** [comment]
This seems nice, but I'm not sure if enough tests(reliability) is there. Also, can you please rebase it?

**Comment by pleb** [comment]
Cool project. I couldn't see any tests. Did I miss them?

**Comment by YaroslavSchubert** [comment]
Rebased. 
Threre is no tests, didn`t notice, sorry.

**Comment by pleb** [comment]
Sorry @YaroslavSchubert, no community feedback and no test. I'm going to close this now.

**Pull request closed without merging**
