### PR TITLE
Some Changes

### PR DESCRIPTION
**Pull request by zandiarash**
There is some updates for GrandNode and  SmartStore

### CODE REVIEW

**Comment by Jogai** [comment]
Seems to me it would be better to take smartstore off the awesome list. Even if they legally did nothing wrong its not so awesome...

**Comment by Arashz22** [comment]
Yes, you are right dude but if SmartStore be in awesome list with that two link which I mentioned, it become more obvious that is legal fork.
and gradually programmers get away from that...

**Comment by pleb** [comment]
Please remove SmartStoreNET

**Comment by Arashz22** [comment]
> 
> 
> Please remove SmartStoreNET

Agree!

**Pull request closed without merging**
