### PR TITLE
Add TinyMapper package

### PR DESCRIPTION
**Pull request by nomailme**

### CODE REVIEW

**Comment by quozd** [comment]
Hey, thank you for your contribution. TinyMapper looks quite good, but I think it will be better to place it to the Misc category. Can you please fix it and I will merge.

**Comment by nomailme** [comment]
Done

**Comment by Jeffiy** [comment]
@quozd We can merge it now?

**Comment by quozd** [comment]
Please resolve the conflicts ;) Then we'll merge it
@nomailme @Jeffiy

**Comment by nomailme** [comment]
Merge conflicts merged :)

**Pull request merged**
