### PR TITLE
Add Misc/MSBuild ILMerge task

### PR DESCRIPTION
**Pull request by wellwind**
Misc/[MSBuild ILMerge task](https://www.nuget.org/packages/MSBuild.ILMerge.Task/) 

MSBuild ILMerge task is a NuGet package allows you to use the famous ILMerge utility in automated builds and/or Visual Studio projects.

### CODE REVIEW

**Comment by Jeffiy** [comment]
@wellwind please update the project site link to https://ilmergemsbuild.codeplex.com/

**Comment by wellwind** [comment]
@Jeffiy : just updated

**Comment by Jeffiy** [comment]
@wellwind thanks, but does it have any document for how to use it ?

**Comment by wellwind** [comment]
@Jeffiy I found this tool from a chinese blog post. And can't find any document writing in English.
However most time you don't have to do anything after install this nuget package. If you dont want to merge some dlls, just set Copy Local = false from Reference.

**Comment by Jeffiy** [comment]
@wellwind well, where is the chinese blog ? I want it. : )

**Comment by Jogai** [comment]
Look @ https://github.com/peters/ILRepack.MSBuild.Task
Its using ilrepack, but has documentation. Isn't that more awesome?

**Comment by wellwind** [comment]
@Jeffiy http://blog.darkthread.net/post-2016-04-06-ilmerge-task-on-vs.aspx

**Comment by Jeffiy** [comment]
@wellwind Thanks.

**Pull request merged**
