### PR TITLE
Add NReco PivotData

### PR DESCRIPTION
**Pull request by VitaliyMF**
Business Intelligence / NReco PivotData - [NReco PivotData](https://www.nrecosite.com/pivot_data_library_net.aspx)

In-memory data aggregation/OLAP library, pivot tables generation (render to HTML, exports), ASP.NET pivot builder control **[$][Free for single-deployment/non-SaaS]**

### CODE REVIEW

**Comment by pleb** [comment]
Sorry, @VitaliyMF,

This entry isn't going to make the list for the following reason(s):

- Community decision required
- No response from the community 😢 

Don't let this setback cause you to lose heart, and we look forward to your next contribution.

Thanks, Pleb

**Comment by VitaliyMF** [comment]
@pleb not sure that I understand what 'response from the community' means - currently [NReco.PivotData](https://www.nuget.org/packages/NReco.PivotData/) nuget package has 15k downloads and this is good tracking for rather niche component like that.

However, I'm ok with either way :-)

**Comment by pleb** [comment]
Let's give it one more chance ;)

**Comment by Jogai** [comment]
It does look awesome. Hard to judge if you dont really use it, but the project looks like its doing really well.

**Pull request merged**
