### PR TITLE
add some libraries from mono

### PR DESCRIPTION
**Pull request by plantain-00**

### CODE REVIEW

**Comment by vladen** [comment]
@plantain-00, since you're introducing the "Compression" section, it's reasonable to migrate "DotNetZip" and "SharpZipLib" from Misc.

**Comment by vladen** [comment]
The "XSP" project can be placed under already existing "Web Servers" section, which reflects the nature of the "XSP" project more precisely (from my perspective).

**Comment by plantain-00** [comment]
@vladen , Thank you, I am glad that someone reviews it.

**Comment by vladen** [comment]
My excuses for delay with reviewing ;)

**Pull request merged**
