### PR TITLE
Added LibSass Host to HTML and CSS

### PR DESCRIPTION
**Pull request by Taritsyn**
HTML and CSS/LibSass Host - https://github.com/Taritsyn/LibSassHost

.NET wrapper around the [libSass](http://sass-lang.com/libsass) library with the ability to support a virtual file system.

### CODE REVIEW

**Comment by Taritsyn** [comment]
First version ([v0.2.0](https://github.com/Taritsyn/LibSassHost/releases/tag/v0.2.0)) of the LibSass Host was released on October 24, 2015.

At the moment, [LibSassHost](https://www.nuget.org/packages/LibSassHost/) package has been downloaded via NuGet 31,286 times. By number of downloads this library bypasses all its competitors: [libsassnet](https://www.nuget.org/packages/libsassnet/), [NSass](https://www.nuget.org/packages/NSass.Core/), [Sass.Net](https://www.nuget.org/packages/XWeb.Web.Sass.Core) and [SharpScss](https://www.nuget.org/packages/SharpScss/).

Starting with [version 1.0.0](https://github.com/Taritsyn/LibSassHost/releases/tag/v1.0.0) the LibSass Host supports .NET Core. In addition, this library is only a .NET wrapper around the libSass, that compatible with Debian-based Linux and OS X.

**Comment by zihotki** [comment]
I also wonder how it fits the modern way of managing web assets and developing web apps in .net where the task of compiling/combining styles and js is delegated to node.js based tools. Since this task needs to be run once to produce a build and since node does a job of managing js and style assets via npm and bower packages and compiling/combining them better, I personally don't see any reason of using this for any but legacy system and system with dynamic styles/scripts.

**Comment by Taritsyn** [comment]
@zihotki How do you feel about the [dotless](https://github.com/dotless/dotless) project (it is present in this collection)?

Wrappers like the LibSass Host exist for almost every programming language or technology - http://sass-lang.com/libsass

**Comment by zihotki** [comment]
@Taritsyn it's seems like it is the most up to date wrapper comparing to other options. Others seems to have no or very minor activity. And also it has good docs

**Comment by Taritsyn** [comment]
@zihotki Thanks!

**Pull request merged**
