### PR TITLE
Adds link for FsCheck

### PR DESCRIPTION
**Pull request by jeremyabbott**
FsCheck is a tool for testing .NET programs automatically. The programmer provides a specification of the program, in the form of properties which functions, methods or objects should satisfy, and FsCheck then tests that the properties hold in a large number of randomly generated cases. While writing the properties, you are actually writing a testable specification of your program. Specifications are expressed in F#, C# or VB, using combinators defined in the FsCheck library. FsCheck provides combinators to define properties, observe the distribution of test data, and define test data generators. When a property fails, FsCheck automatically displays a minimal counter example.

### CODE REVIEW

**Comment by quozd** [comment]
Conflicts, sir ;) Please, resolve them and I will merge

**Comment by Jeffiy** [comment]
@jeremyabbott can you resolve the conflicts ?

**Comment by jeremyabbott** [comment]
Oops, sorry! Fixing it now.

**Comment by jeremyabbott** [comment]
You should be good to go. I'm sorry for not getting back to it sooner.

**Pull request merged**
