### PR TITLE
Added Minification category

### PR DESCRIPTION
**Pull request by Taritsyn**
I propose to create the “Minification” category and add the following projects:

* [Microsoft Ajax Minifier](http://ajaxmin.codeplex.com/) - Contains JS and CSS minifiers which have a highest performance, because its have been specifically designed for .NET. Optionally produce Source Maps for JS code.
* [Web Markup Minifier](http://webmarkupmin.codeplex.com/) - .NET library that contains a set of markup minifiers. The objective of this project is to improve the performance of web applications by reducing the size of HTML, XHTML and XML code.

### CODE REVIEW

**Comment by pleb** [comment]
Hi @Taritsyn. Thanks for the contribution. 

Unfortunately there's a few problems with this commit, and we require a few changes before we can accept it. The [guide](https://github.com/quozd/awesome-dotnet/blob/master/CONTRIBUTING.md) for contributing requests to `Submit one pull request with one link per PR`. In addition, the guide also requests to `Include a link to the added project in the PR description`.

**Comment by Jeffiy** [comment]
@plen It's ok, because `all of the proposed projects are belong to the same category`.

**Comment by pleb** [comment]
@Jeffiy @Taritsyn, yep @Jeffiy is absolutely right. I missed that bit.

**Comment by Taritsyn** [comment]
@pleb @Jeffiy Added description to PR.

**Comment by Jeffiy** [comment]
@Taritsyn Thanks, but the last update of `YUICompressor.NET` is a year ago, looks like it's died.

**Comment by Taritsyn** [comment]
@Jeffiy YUI Compressor for .NET is still very popular JS/CSS minifier in .NET community. Look at the [statistics of its downloads](https://www.nuget.org/stats/packages/YUICompressor.NET?groupby=Version).

**Comment by Taritsyn** [comment]
Removed a YUI Compressor for .NET fom PR.

**Comment by Jeffiy** [comment]
@Taritsyn thanks. Looks like you may have a line ending issue, because  `+675 and -669` changes. Can you please fix and we'll be happy to consider the PR

**Pull request closed without merging**
