### PR TITLE
Add RavenDB - A linq enabled document database for .NET

### PR DESCRIPTION
**Pull request by VPashkov**

### CODE REVIEW

**Comment by quozd** [comment]
@VPashkov if we are going to create the new category, we should also move all related links to it. 
Please, move Mono.Cecil to Reflection category as well as Fody.

**Comment by VPashkov** [comment]
Oh sorry, I didn't mean to add Fody in this pull request.
It's only for RavenDB.
Fixed.

**Comment by vladen** [comment]
Btw,  Fody is awesome too, isn't?

**Comment by VPashkov** [comment]
Yes, definitely!
Just thought to split pull requests - one for RavenDB and one for Fody and new [Reflection] category.

**Pull request merged**
