### PR TITLE
Added some useful libraries

### PR DESCRIPTION
**Pull request by wind39**

### CODE REVIEW

**Comment by quozd** [comment]
Hello, thank you for your contribution. A few notes about proposed projects:

1. ZipStorer is outdated. Latest commit is in 2012 and there is no any activity. It violates our [Contribution guidelines](https://github.com/quozd/awesome-dotnet/blob/master/CONTRIBUTING.md). We can not accept this project, please remove it.
2. I cannot find Firebird.NET repo. Is it public? It will be better to have direct link to the repo. Anyway, we'll accept this project.
3. Ovule.Nomad is too young. We can't accept it right now, but we should definitely consider adding it in the future.
4. Eto.Forms :+1: 
5. Spartacus violates our Contribution guidelines. It's not mature yet, has no documentation and test. We can't accept it right now.
6. PDFjet.NET is proprietary library, right now we don't have any guidelines for proprietary software. That's why we don't accept such projects. Feel free to open a discussion about paid libraries and propose guidelines about how not to make our list full of ads.

Please, fix your PR and well merge it. Thank you.

**Comment by wind39** [comment]
- Firebird.NET repo is on sourceforge, where it is actively maintained. I changed the link.
- Removed ZipStorer. I use it nowadays on active projects, though. But I agree all projects on this list need to be actively maintained.
- Removed PDFjet. I'm not going to open a discussion about proprietary libraries, I agree it will become too hard to avoid ads.
- Removed Spartacus
- Removed Ovule.Nomad

Please note: I'm creator and maintainer of Spartacus, and I contribute to Ovule.Nomad. Soon they will grow and we'll be able to add them to the list :)

**Comment by quozd** [comment]
Thank you. Could you please resolve conflicts as well so we can use automatic merge? :)

Btw, there already is closed discussion about proprietary software #4 Feel free to reopen it and comment.

**Comment by wind39** [comment]
Due to conflicts I needed to refork. Please consider [#98](https://github.com/quozd/awesome-dotnet/pull/98). I'm closing this one.

**Pull request closed without merging**
