### PR TITLE
Workflow Core

### PR DESCRIPTION
**Pull request by danielgerlag**
Workflow Engines/Workflow Core - [WorkflowCore](https://github.com/danielgerlag/workflow-core)

Workflow Core is a light weight workflow engine targeting .NET Standard. Think: long running processes with multiple tasks that need to track state. It supports pluggable persistence and concurrency providers to allow for multi-node clusters.

** Also added `Workflow Engines` category

### CODE REVIEW

**Comment by zihotki** [comment]
Hey, Thank you very much for the PR. The project is definitely awesome but I prefer to add new categories after some discussion to keep categories under control. Let's see what other mods/people say

**Comment by danielgerlag** [comment]
@zihotki which category would you suggest?

**Comment by danielgerlag** [comment]
@zihotki ? @quozd ? somebody? anybody?

**Comment by zihotki** [comment]
Hey, sorry for delay. I'd consider putting it into Scheduling category alongside the similar workflow frameworks. Or we can introduce a new category and move workflow frameworks from Scheduling to new category.

**Comment by danielgerlag** [comment]
done 😄

**Pull request merged**
