### PR TITLE
Added link to cryptographic library Inferno.

### PR DESCRIPTION
**Pull request by exyi**
Cryptography/SecurityDriven.Inferno - http://securitydriven.net/inferno/

Inferno is easy to use abstraction over .NET crypto primitives.

Added link to cryptographic library Inferno.

### CODE REVIEW

**Comment by Jeffiy** [comment]
@exyi I can't find any test :open_mouth:

**Comment by pleb** [comment]
Agree with @Jeffiy on this one. Considering it's security related and all.

@exyi are one of the maintainers?

**Comment by pleb** [comment]
Closing. Does not have tests

**Comment by sdrapkin** [comment]
@Jeffiy @pleb Sorry for intruding on this "awesome-dotnet" thing - I want to point out that [Inferno](http://securitydriven.net/inferno/) **has** tests: https://github.com/sdrapkin

**Pull request closed without merging**
