### PR TITLE
Add Fody and move Mono.Cecil to Reflection category

### PR DESCRIPTION
**Pull request by VPashkov**

### CODE REVIEW

**Comment by gep13** [comment]
Great additions! /cc @simoncropp :+1:

**Comment by quozd** [comment]
Good job :+1:

**Comment by SimonCropp** [comment]
Not sure fody should be in reflection

**Comment by quozd** [comment]
@SimonCropp feel free to propose better section :) We're alway open for contributions.

**Comment by VPashkov** [comment]
@SimonCropp may be AOP section will suit better?

**Comment by SimonCropp** [comment]
@VPashkov  i think "Assembly manipulation" is better since then that covers Cecil and Fody. Also technically, while you can achieve AOP with fody, it is not just AOP. For example this https://github.com/Fody/Caseless has no "apsect".

**Comment by VPashkov** [comment]
@SimonCropp Agreed. Thanks.

**Comment by quozd** [comment]
Good. Thanks guys.
@VPashkov can you please move Fody and Cecil to the new section. Then I will merge.

**Pull request merged**
