### PR TITLE
CatLight build status notifier

### PR DESCRIPTION
**Pull request by catlightio**
Tools/CatLight - https://catlight.io 

Build status notifications for TFS/Jenkins/Travis/Appveyor. Cross-platform desktop app based on .Net Core and Electron.

### CODE REVIEW

**Comment by devkhan** [comment]
Is it free/open source/proprietary?

**Comment by catlightio** [comment]
It's free, but not open-source

**Comment by devkhan** [comment]
Please add the relevant tags according to [this](https://github.com/quozd/awesome-dotnet/blob/master/CONTRIBUTING.md#proprietarycommercial-software-notice).

**Comment by devkhan** [comment]
👍

**Pull request merged**
