### PR TITLE
Add NDepend

### PR DESCRIPTION
**Pull request by CoderGears**
[NDepend] (http://www.ndepend.com/) - NDepend is a Visual Studio and VS Team Services extension that estimates your .NET code quality and Technical-Debt, that lets create code rules with C# LINQ syntax, visualize code structure and focus on changes and evolution. **[$]**

### CODE REVIEW

**Comment by quozd** [comment]
@CoderGears, please reformat NDepend entry according to our guildelines for commercial projects which you can find here https://github.com/quozd/awesome-dotnet/blob/master/CONTRIBUTING.md#proprietarycommercial-software-notice

After that, we can merge you PR

**Comment by CoderGears** [comment]
It's done.
Thanks.

**Comment by quozd** [comment]
@CoderGears, please do it in your commit (README.md), not in the PR message. We require proprietary marks to be in the list.

**Comment by CoderGears** [comment]
ok it's done

**Pull request merged**
