### PR TITLE
Add Signum Framework

### PR DESCRIPTION
**Pull request by olmobrutall**
Application Frameworks, ORM, GUI/Signum Framework - [http://www.signumsoftware.com/en/Framework](http://www.signumsoftware.com/en/Framework)

Full stack framework for writing data-centric applications. Uses C#, LINQ, Typescript, React and Bootstrap (or WPF). Promotes reusing modules in different applications while being 100% statically-typed. Signum Extensions contains 24 ready-to-use modules.

Note: The scope of the framework is very big, covering from DB to UI, so I added tree different descriptions in three categories (Application Frameworks / ORM / GUI).

### CODE REVIEW

**Comment by olmobrutall** [comment]
Looks like the problem is unrelated to my commit

**Comment by Jogai** [comment]
Is it truly awesome? I'm asking because I heard about it yesterday for the first time but dont see much talk about it.

**Comment by olmobrutall** [comment]
It's true that is not known. Aside from a some local conferences in Spain and Germany we haven't made any publicity. We have also been trying to monetize it unsuccessfully. Now is LGPL. 

It's also too big too add it to an already build project, limiting his popularity. It's not based in the buzzwords of the moment or supported by any big brand, so it's a risky decision for developers. 

On the other side, is a framework for building solid line of business applications for windows and web based on a database. Focusing more in making maintainable applications on the long run than in a easy drop-in experience. As the main author of it, and after spending about 7 years building it (before Entity Framework), i can tell you that is quite awesome. 

Let me enumerate some facts/features in not particular order: 

Project: 
* I'm aware of it being used in about 20 big enterprise applications in 8 different companies of 6 different countries. We know most of the developers using it personally and since now none was ever reimplemented in another technology. 
* more than 7 years of uninterrupted work
* automatic applicator generator from an always up to date example application (Southwind) http://www.signumsoftware.com/en/DuplicateApplication
* more than 400 unit test (for the LINQ provider) and very cold technology to create UI test in c# using UIAutomation/Selenium
* reasonably well documented http://www.signumsoftware.com/Documentation/framework/master/Introduction.md
* active Gitter channel/isssue tracker
* very good tooling, with code snippets and some Roslyn analyzer a and code fixes. 


Signum Framework: http://www.signumsoftware.com/en/Framework
* C# with functional style 
* 100% strongly typed
* Code first approach 
* Validation in the entities 
* Automatic SQL migrations 
* VERY powerful LINQ provider with correlated subqueries (aka N+1), reusing subexpressions and massive updates/deletes/inserts without materializing anything. 
* awesome UI developers experience in windows (WPF) and web (Typescript 2 and React) thanks to Schema integration of the custom controls: automatic autocomplete, integrated security, localization, UTC support...
* Very powerful search control (grid) that lets the end user order, filter, add columns even in other tables, explore collections...
* very useful new concepts and patterns, like Lite<T>, Mixins, Operations or Symbols. 

Signum Extensions: http://www.signumsoftware.com/en/Extensions

* Authorization with users, roles and rules to restrict access to tables, columns and even rows (using where expressions) that are globally applied. 
* Multi tenant support, for applications that have to support independent customers in the same database (SAS). 
* awesome charting library integrated with the search control. 
* dashboards
* localization
* word reports generator and email templates 
* .... like 20 modules more.
* recently we're working on creating workflows and dynamic entities for per-customer customizations. 

Definitely the framework is very big and this scares many developers, specially if not promoted by Microsoft, Google or Facebook, and not everything is documented but there is in there a LOT of awesome stuff for the brave ones. 

Since is distributed as git submodules, is very easy to debug/understand/contribute. 

Finally the framework pushes the applications to evolve with the technology, that's why is 7 years old but using TS2, React and c# 6.

**Comment by pleb** [comment]
I wonder if three links are excessive? Maybe a new category for large frameworks such as this?

**Comment by Jogai** [comment]
@olmobrutall You were just waiting for someone to ask this, no? 😄 

Thanks for answering. Maybe not based on buzzword, but it looks fine using TS2 etc.

**Comment by olmobrutall** [comment]
@pleb, Application frameworks VS Full Stsck Framewprks maybe?? It's kind of a gray area. 

Maybe removing it from the GUI, but I think it absolutely deserves a place in ORM. Anybody can make a micro ORM in a week or two, but implementing a full LINQ provider is a different story. The ORM is also the core of Signum framework.

**Comment by olmobrutall** [comment]
@Jogai thanks jogai. If you're interested in TS, just mention that is using it with all the script flags enabled, like notImplicitAny or even strictNullCheck. https://github.com/Microsoft/TypeScript/issues/9653

**Comment by pleb** [comment]
My main concern with the PR is the reuse of the same link `https://github.com/signumsoftware/framework` multiple times. Other mods - thoughts?

**Comment by olmobrutall** [comment]
Removing it from GUI is enough? Or should we create another category for full stack frameworks? Are there any other full stack framework out there?

**Comment by pleb** [comment]
@olmobrutall it's an interesting situation. I'd prefer if the other mods chime in with their thoughts. Personally, I'm torn between a full stack section or multiple links. In both situations there are pros and cons.

**Comment by olmobrutall** [comment]
Let's take one of the two decisions and refactor if it becomes out of control?

**Comment by quozd** [comment]
As for me, adding multiple links is not fair. Lot's of other projects can be added to several categories, but we always add a link to the most relevant one.

I think this should go into Application frameworks category. This category is the best suited for such libraries. As far as I understand Signum was not designed as a GUI or ORM library only. It was designed as a complete solution. So it should be under frameworks.

**Comment by zihotki** [comment]
Agree, main focus of it is to be an Application framework. If the owners decide to split it into multiple libraries - ORM, GUI, etc. then each separate project can be put into apropriate section. But for now Application fits it the best

**Comment by pleb** [comment]
Not much happening on this. Closing ticket as PR has not been updated to place link under Application frameworks category

**Pull request closed without merging**
