### PR TITLE
Database/EsentSerialize

### PR DESCRIPTION
**Pull request by Const-me**
Database/EsentSerialize -
[EsentSerialize](https://github.com/Const-me/EsentSerialize)

A .NET NoSQL table / document store on top of
https://en.wikipedia.org/wiki/Extensible_Storage_Engine

### CODE REVIEW

**Comment by pleb** [comment]
@Const-me I didn't see any tests. Did I miss them?

**Comment by Const-me** [comment]
In the “Demos” folder of the repository, you will find eight projects testing various parts of the library. Including relatively complex ones, like implementing a client-server on top of that, or doing a DB schema upgrade.

The project was migrated from codeplex. The commit history there dates back to 2012: http://esentserialize.codeplex.com/SourceControl/list/changesets?page=3

**Comment by zihotki** [comment]
But the demos are not tests. It should have automated integration tests at least.

**Comment by Const-me** [comment]
Please take a look there: https://github.com/Const-me/EsentSerialize/blob/master/Demos/ConsoleDemo/Program.cs
That's a command-line application that requires no user input (i.e. automated), creates a test database with some records, runs queries on the database, and prints the results.

Why exactly you think that’s not an automated integration test? Just because no dependency on NUnit/XUnit? :-)

**Comment by zihotki** [comment]
That's just a demo, but not a test. Automated test by definition should automatically run a function in predefined context and automatically check correctness of function result. Demo != test.

**Comment by pleb** [comment]
@Const-me 

Sorry, I'm going to close this one. 

I partially agree that Demo code may be considered a form of testing.

The primary reason why I'm closing this is due to the niche nature of this library.

**Pull request closed without merging**
