### PR TITLE
add SmartSql ORM

### PR DESCRIPTION
**Pull request by Ahoo-Wang**
ORM/SmartSql - [https://github.com/Ahoo-Wang/SmartSql](https://github.com/Ahoo-Wang/SmartSql)

PROJECT_DESCRIPTION

## 0. Why ?
 - 拥抱 跨平台 DotNet Core，是时候了。 
 - 基于Dapper，不再重复造轮子。Dapper性能你懂的。
 
## 1. So SmartSql
 - TargetFramework: .NETStandard,Version=v1.4
 - SmartSql = Dapper + MyBatis + Cache(Memory | Redis) + ZooKeeper + R/W Splitting + ......

## 2. 主要特性 (√ 为已完成，未打 √ 为计划特性)
- 1 ORM 
  - 1.1 Sync √
  - 1.2 Async √
- 2 XmlConfig & XmlStatement -> Sql  √
  - 2.1 SmartSqlMapConfig & SmartSqlMap √  (是的，你猜对了，和MyBatis一样，通过XML配置分离SQL。)
  - 2.2 Config Hot Update ->ConfigWatcher & Reload √ (配置文件热更新：当你需要修改Sql的时候，直接修改SqlMap配置文件，保存即可。)
- 3 读写分离 √
  - 3.1 读写分离 √ 
  - 3.2 多读库 权重筛选 √ （配置多读库，根据读库权重选举读库）
  - 3.3 读库故障检测,剔除 
- 4 Logging √
  - 4.1 NLog √ （当你需要跟踪调试的时候一切都是那么一目了然）
- 5 DAO
  - 5.1 DAO √
  - 5.2 DAO Tool  √
    - 5.2.1 Template Xml & Entity & DAO  √
    - 5.2.2 Generate Tool  √
- 6 Query Cache  √
  - 6.1 SmartSql.Cache.Memory  √
      - 6.1.1 Fifo  √
      - 6.1.2 Lru  √
  - 6.2 SmartSql.Cache.Redis  √
  - 6.3 缓存事务一致性  √
- 7 分布式配置插件 
  - 7.1 IConfigLoader  √ (配置文件加载器)
  - 7.2 LocalFileConfigLoader  √ (本地文件配置加载器)
  - 7.3 SmartSql.ZooKeeperConfig √ (ZooKeeper 分布式配置文件加载器)

### CODE REVIEW

**Comment by SlowLogicBoy** [comment]
Is there English documentation for this project?

**Comment by Ahoo-Wang** [comment]
@SlowLogicBoy English documentation is already in the works.

**Comment by Jeffiy** [comment]
@Ahoo-Wang LGTM，看着还不错

**Comment by zihotki** [comment]
It's really hard to evaluate the project when there is no English documentation. But the project looks promising

**Comment by zihotki** [comment]
Since July there was no progress about documentation at all, tests are sort of present but not complete and it's not possible to use them as a learning source and there are no samples. Most of comments are not in English and commit messages are just 'u' messages. Considering all of this I closing the PR. We'd love to include it when the quality of documentation, tests, samples, etc. is improved.

**Pull request closed without merging**
