### PR TITLE
adding simple.data as orm

### PR DESCRIPTION
**Pull request by lfreneda**
:v:

### CODE REVIEW

**Comment by quozd** [comment]
Hi @lfreneda thank you for your contribution. Unfortunately we can not accept this PR because Simple.Data is almost dead. Half of issues are left unanswered, no commits for a log time.

**Comment by lfreneda** [comment]
Okay :cry:

**Comment by gep13** [comment]
@markrendle would you consider Simple.Data dead?

**Comment by markrendle** [comment]
No, I'm slowly working on 2.0, just got a lot of other stuff going on
besides.

*Mark Rendle*
*Founder,* *Zudio* <https://zud.io/>

**Comment by lfreneda** [comment]
Should I reopen this PR @quozd ?

**Comment by quozd** [comment]
@lfreneda I'm still not sure about adding it to the list. It violates our [Contribution guidelines](https://github.com/quozd/awesome-dotnet/blob/master/CONTRIBUTING.md) which stands that project should be actively maintained. What I can see in the repo - a lot of issues and PR are unanswered. Work on v2.0 is too slow (just 2-3 commins per half a year https://github.com/markrendle/Simple.Data/commits/v2). 

@vladen what do you think?

**Comment by vladen** [comment]
Great work was done on this project. Hope it will have its fresh breathe again soon and evolve to the next level of awesomeness. Perhaps, adding to the list will help this project find new contributors who'll be able to speed it up. IMHO dynamic ORM is one of the most comfortable ways to talk to a database from statically typed language without all that tiresome/cumbersome stuff around.

**Comment by markrendle** [comment]
Hi, I'm the lead developer of Simple.Data.
I think it's fair that the project has fallen off the list; it has stalled
recently, no question.
I am still working on v2, and I hope to release a beta in July or August. Much
of the delay is down to wanting v2 to work with .NET Core, and some of the
dependencies I have are not available yet.
Once I get properly back underway, I hope Simple.Data v2 will make it back onto
this list. I think some of the stuff going into it is going to be really cool.
Cheers, Mark

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.1]
On Tue, Jun 16, 2015 at 16:14, quozd/awesome-dotnet
<reply@reply.github.com>
wrote:
Great work was done on this project. Hope it will have its fresh breathe again
soon and evolve to the next level of awesomeness. Perhaps, adding to the list
will help this project find new contributors who'll be able to speed it up. IMHO
dynamic ORM is one of the most comfortable ways to talk to a database from
statically typed language without all that tiresome/cumbersome stuff around.

—
Reply to this email directly or view it on GitHub
[https://github.com/quozd/awesome-dotnet/pull/109#issuecomment-112446724] .[https://github.com/notifications/beacon/AAK4QpcT_EBLEH-M-EY_aclKIObqmNAAks5oUCbagaJpZM4FDcQN.gif]

**Comment by quozd** [comment]
OK guys. I will reopen this PR and leave it opened for month or two. I really like Simple.Data project and will be happy if it get new life. Then I will proudly merge this PR.

@markrendle thanks for clarification and happy hacking :)

**Comment by lfreneda** [comment]
yay :dancers:

**Comment by Jeffiy** [comment]
@markrendle Hi, are you still working on it ? I notice there are 10 PR and 59 issues still opening.

**Comment by quozd** [comment]
Looks abandoned

**Comment by lfreneda** [comment]
sad

**Pull request closed without merging**
