### PR TITLE
LinqKit and SQLProvider. https://github.com/scottksmith95/LINQKit and…

### PR DESCRIPTION
**Pull request by Thorium**
CATEGORY/PROJECT_NAME - [PROJECT_LINK](PROJECT_LINK)

PROJECT_DESCRIPTION
Orm/LinqKit - https://github.com/scottksmith95/LINQKit
Orm/SQLProvider - https://github.com/fsprojects/SQLProvider

These are two quite common database tools that I would say could be categorized under orm-category: not pure orms, but have orm-like functionality.

### CODE REVIEW

**Comment by pleb** [comment]
Hi @Thorium. 

Thanks for the PR. 

However, before we look at it you'll need to bring it up to our contribution standard. You can read about how we require a PR to be submitted [here](https://github.com/quozd/awesome-dotnet/blob/master/CONTRIBUTING.md). 

Again, thanks for taking the time to contribute to this project. We hope to hear from you soon

**Comment by Thorium** [comment]
I did read those instructions before the commit. So I don't know what I did wrong...

**Comment by Thorium** [comment]
Missing these two packages of total over 510 000 downloads in NuGet, is just incompleteness of this list. If you can add those according your bureaucracy and policies it would be nice.

**Comment by pleb** [comment]
@Thorium - The part you missed while reading the instructions was `Submit one pull request with one link per PR`. Thanks.

**Pull request closed without merging**
