### PR TITLE
added appveyor

### PR DESCRIPTION
**Pull request by ghuntley**

### CODE REVIEW

**Comment by gep13** [comment]
:+1: 

FYI @FeodorFitsner

**Comment by quozd** [comment]
Hi @ghuntley , thank you for your contribution.

@vladen what do you think about this project? It's free for OSS, but I don't want to make our list full of ads. Maybe we should remove Teamcity from the list to stay OSS as much as possible.

Similar with #96

**Comment by vladen** [comment]
Can't find the "30-page guide on "How to setup CI for your project in 1 month" (: I'd like to have a look on it.

**Comment by vladen** [comment]
It's awesome thing! Let's create another list for good software with mixed licensing.

**Comment by quozd** [comment]
@ghuntley I've added contribution guidelines for a proprietary software. Please, change your PR to comply with these requirements before we can merge it.

**Comment by quozd** [comment]
@ghuntley will you update this PR so I can merge it?

**Comment by ghuntley** [comment]
Ready for merge.

**Pull request merged**
