### PR TITLE
Add entry for ReportUnit - report generator for tests

### PR DESCRIPTION
**Pull request by caioproiete**
ReportUnit is a report generator for the test-runner family. It uses stock reports from NUnit, MSTest and Gallio and converts them into attractive HTML reports with dashboards.

https://github.com/reportunit/reportunit

### CODE REVIEW

**Comment by quozd** [comment]
Hello, thank you for your contribution. Unfortunately this projects is too young and immature and doesn't comply with our quality standards. We will be happy to merge it in the future :)

**Comment by caioproiete** [comment]
Hello again @quozd, ReportUnit is not young and/or immature... [It used to be called NUnitOrange, and have been renamed to ReportUnit several months ago](http://relevantcodes.com/nunit-orange-nunit-html-report-generator/).

**Comment by quozd** [comment]
Hello @caioproiete. Hmmm, now it looks better, but I'm still in doubt. I can't see any test coverage which can ensure that nothing will be broken on new releases and there are no documentation, so I can't customize the output. Are you sure that the project won't be abandoned and is stable enough?

cc @vladen, @devkhan

**Comment by quozd** [comment]
cc @Jeffiy

**Comment by Jeffiy** [comment]
Not sure about it.

**Comment by quozd** [comment]
OK, lets wait for some time :)
@caioproiete we'll be glad to see this PR later, when project will comply with our contribution policies.

**Pull request closed without merging**
