### PR TITLE
Adding AudioControl

### PR DESCRIPTION
**Pull request by devmartins**
Media/AudioControl - [AudioControl](https://github.com/devmartins/AudioControl)

Library for volume control of the main audio in Windows 10.

### CODE REVIEW

**Comment by devmartins** [comment]
Hi zihotki, yes the project is small, because it's a library and it's awesome because I took hours to find this code. So I built this package. Let the news come to the community.

**Comment by Jogai** [comment]
I dont even like the label "too small" but for this one it seems justified. I expected something like https://github.com/xenolightning/AudioSwitcher

**Comment by pleb** [comment]
@Jogai re the labels. 

Yes, I see what you mean. I created these labels awhile ago and didn't give too much thought to them. My main concerns at the time were, labels to make grooming PRs easier and labels which non-native English speakers would easily understand.

Maybe it's time to create a GH Issue where we can discuss and tweak them. Would you be interested?

**Comment by pleb** [comment]
Sorry @devmartins,

This entry isn't going to make the list.

Don't let this setback cause you to lose heart, and we look forward to your next contribution.

Thanks, Pleb

**Pull request closed without merging**
