### PR TITLE
Add ConsoleTableExt

### PR DESCRIPTION
**Pull request by minhhungit**
MISC/ConsoleTableExt - [ConsoleTableExt](https://github.com/minhhungit/ConsoleTableExt)

A fluent library to print out a nicely formatted table in a console application C#

### CODE REVIEW

**Comment by SlowLogicBoy** [comment]
No netstandard ;( ?

**Comment by minhhungit** [comment]
@SlowLogicBoy  Will support netstandard in near future, if you need it now then just copy code to your project

**Comment by minhhungit** [comment]
@SlowLogicBoy .net standard 2.0 is supported, check it here:

> Install-Package ConsoleTableExt -Version 2.0.0

**Comment by zihotki** [comment]
Great addition. It'd become even better if you can add some unit tests.

**Comment by minhhungit** [comment]
@zihotki I will add it soon, thank you for your suggestion!

**Pull request merged**
