### PR TITLE
add AjaxService.Gen

### PR DESCRIPTION
**Pull request by MrAliSalehi**
Source Generator/AjaxService.Gen- [https://github.com/MrAliSalehi/AjaxService](https://github.com/MrAliSalehi/AjaxService)

AjaxService is a source-generator, it can generate **ajax** calls in *typescript* **based** on your c\# *Api endpoints*.

### CODE REVIEW

**Comment by MrAliSalehi** [comment]
is there any problems with this commit that doesn't get merged?

**Comment by pleb** [comment]
Hi @MrAliSalehi. The reason why it wasn't approved is the project needs to mature a little more to satisfy the [Quality section for contributions](https://github.com/quozd/awesome-dotnet/blob/master/CONTRIBUTING.md#quality-standard)

Good luck :) and feel free to reopen in the future

**Comment by MrAliSalehi** [comment]
@pleb its documented, tested and stabilized, I dont know how it would not be useful or who decides that, anyway, GL to you too

**Comment by pleb** [comment]
@Jogai thoughts?

**Pull request closed without merging**
