### PR TITLE
Add Fluent Command Line Parser

### PR DESCRIPTION
**Pull request by kdelmonte**
This library does what it promises and it is incredibly simple to understand. If you take 5 minutes to read the README you are already an expert which is awesome.

### CODE REVIEW

**Comment by canton7** [comment]
There's a lot of noise in your commit: I think you editor stripped trailing whitespace.

**Comment by quozd** [comment]
@canton7 That's ok. 

@kdelmonte Thank you

**Comment by kdelmonte** [comment]
Thanks. I think it was git that converted all the \r\n's to \n's.

Ping @siywilliams

**Comment by siywilliams** [comment]
Woah thanks @kdelmonte

**Pull request merged**
