### PR TITLE
Update redirects in Readme

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### CODE REVIEW

**Comment by Jeffiy** [comment]
Conflicts, sir ;) Please, resolve them and we will merge, Thanks.
BTW it's a amazing tool.

**Comment by ReadmeCritic** [comment]
Unfortunately rebase is not supported yet, will close and reopen..

**Comment by gep13** [comment]
>@ReadmeCritic said...
Unfortunately rebase is not supported yet, will close and reopen..

I am curious, what exactly do you mean by rebase is not supported?

**Comment by ReadmeCritic** [comment]
I am using a tool for this and rebasing / resolving conflicts is not yet supported by it :smile:

**Comment by gep13** [comment]
>@ReadmeCritic said...
I am using a tool for this and rebasing / resolving conflicts is not yet supported by it :smile:

I don't think I have ever found a tool that helps with rebasing (in a way that makes sense, especially when it comes to interactive rebases).  This is always something that I drop to the command line to do.  It isn't that hard to achieve, and I would suggest that this is something that you need to add to your arsenal of git knowledge, as it will come up again and again.

**Pull request closed without merging**
