### PR TITLE
Add Misc\TinyMessenger

### PR DESCRIPTION
**Pull request by CrazyAlex25**
Misc\TinyMessenger https://github.com/grumpydev/TinyMessenger 
- A lightweight event aggregator/messenger for loosely coupled communication. Single file!

### CODE REVIEW

**Comment by pleb** [comment]
Seems like we need a new category. I can see MediatR, and Mediator.Net lumped in MISC. @CrazyAlex25 do you think you can add a cat and move the others along with your addition?

**Comment by CrazyAlex25** [comment]
New category is "Event aggregator/Messenger "?  There are projects like [Rx Event Aggregator](https://mikebridge.github.io/articles/csharp-domain-event-aggregator/) and [RedBus](https://github.com/mxjones/RedBus). But RedBus Latest commit  on 19 Dec 2015.

**Comment by CrazyAlex25** [comment]
I create new PR with new category #571

**Comment by pleb** [comment]
Cheers buddy

**Pull request closed without merging**
