### PR TITLE
Replace DotNetZip by DotNetZip.Semverd

### PR DESCRIPTION
**Pull request by guillaume-fr**
Fixes https://github.com/quozd/awesome-dotnet/issues/83
DotNetZip no longer maintained

### CODE REVIEW

**Comment by vladen** [comment]
Tend to agree. Maybe it worth to keep the legacy link as well? For historical reasons, priority right or something like this. Furthermore, the original repo (codeplex) contains a lot of useful information.

**Comment by quozd** [comment]
@vladen @guillaume-fr +1 for keeping link to old repo. It can be just link in the end of description like `An open-source project that delivers a .NET library for handling ZIP files, and some associated tools. (fork of http://link/to/old/repo`

**Comment by quozd** [comment]
@guillaume-fr are you going to change the description as I suggested?

**Comment by guillaume-fr** [comment]
@quozd done !

**Comment by quozd** [comment]
Thank you.

**Comment by haf** [comment]
@guillaume-fr it's maintained, but it's through PRs only

**Comment by haf** [comment]
I suggest we remove the 'fork' as that seems to imply there's still some activity in the original repo, which there is not.

**Comment by quozd** [comment]
@haf I would like to keep link to original Codeplex repo as it contains some patches and discussions which can be useful.

**Comment by guillaume-fr** [comment]
When I said the project is no longer maintained I was talking about the original repo. The fork is maintained (thank you @haf ;-) ).

The fork already contains a link to the original version (see release notes in README.md). If we really want to keep the link here, we may specify that the original version is unmainted.

> fork of [**Unmaintained** DotNetZip](http://dotnetzip.codeplex.com)

**Comment by quozd** [comment]
Hm, good idea. PR is welcome :)

**Comment by guillaume-fr** [comment]
https://github.com/quozd/awesome-dotnet/pull/86

**Pull request merged**
