### PR TITLE
Add RestEase to HTTP

### PR DESCRIPTION
**Pull request by canton7**

### CODE REVIEW

**Comment by quozd** [comment]
Hey, thank you for your contribution. Im not sure about this one. @vladen what do you think?

**Comment by vladen** [comment]
Cool stuff. I would enjoy it. Very handy declarative REST client with great example of code emitting under the hood.

**Comment by canton7** [comment]
Thanks! :smile: 

Rebased on top of master.

**Comment by quozd** [comment]
Thank you, merged.

**Pull request merged**
