### PR TITLE
Adding SqlKata

### PR DESCRIPTION
**Pull request by ahmad-moussawi**
Database/SqlKata - [SqlKata](http://sqlkata.vivida-apps.com) 

SqlKata - Elegant Sql Query Builder, that supports complex queries, joins, sub queries, nested where conditions, vendor engine targets and more

### CODE REVIEW

**Comment by zihotki** [comment]
I think that ORM section will be a better fit for the framework. Databases section contains databases and core frameworks to work with databases but SqlKata is a query builder which works on top of standard Sql stack.

**Comment by pleb** [comment]
I think this project is awesome because

1. Nice site
2. Nice documentation
3. Not that many query builders I know of written for dotnet

My suggestion would be a new category under DB - Database query builders. The reason for this suggestion is that, as @zihotki states, it's not really a great fit for Databases. But, I think the same can be said for ORMs. 

If we add this category, we should move another query builders listed.

Thoughts?

**Comment by ahmad-moussawi** [comment]
Agree with @pleb, a new category for query builders would be more appropriate, since now it cannot be considered as ORM

**Comment by pleb** [comment]
@ahmad-moussawi can you update the PR pls. I'll merge when placed under new cat

**Comment by ahmad-moussawi** [comment]
@pleb, updated thanks.

**Pull request merged**
