### PR TITLE
Add IoC \ TinyIoc

### PR DESCRIPTION
**Pull request by CrazyAlex25**
IoC \ TinyIoc https://github.com/grumpydev/TinyIoC
An easy to use, hassle free, Inversion of Control Container for small projects, libraries and beginners alike. Single file!

### CODE REVIEW

**Comment by SlowLogicBoy** [comment]
We just removed this because this is no longer supported.

**Comment by CrazyAlex25** [comment]
So from this he did not stop working. I use this because there are no external relocations, just one file and easy use

**Comment by SlowLogicBoy** [comment]
I also use this extensively

**Comment by pleb** [comment]
Looks like it's not maintained anymore. I've used this a few times too.

@grumpydev say it isn't so?

**Comment by kiquenet** [comment]
Any full real world samples using It?

**Comment by CrazyAlex25** [comment]
TinyIOC can be used in PCL and Xamarin.

**Comment by SlowLogicBoy** [comment]
Nancy uses TinyIoC as default IoC container

**Comment by grumpydev** [comment]
Its not abandoned no, it's actively used as Nancy's default container for one. There are a few reasons it hasn't been updated for a while. Firstly, the last year or so, for various personal and professional reasons, I've had very little time for OSS work. Secondly, the version in Nancy I *think* has diverged from the version in the main repo, so I need to consolidate before I do much more work on it, and finally I have (thankfully I think) managed to avoid any of the .net core/standard/vnext stuff so far, and the main "issues" I see discussed are all around that, although Nancy itself supports netstandard with TinyIoC inside, so I think that issue is "ok", but referring back to the previous point.

After the consolidation I intend to work on the way the child containers work, as currently you have to make registrations directly in the child container, rather than being able to specify a "child lifetime" on the parent container (which would be more efficient and less code for the consumers).

**Comment by pleb** [comment]
@grumpydev sounds awesome. And, thanks for the update.

**Pull request merged**
