### PR TITLE
Add DynamicImage

### PR DESCRIPTION
**Pull request by tgjones**

### CODE REVIEW

**Comment by quozd** [comment]
Hi, thanks for your contribution. Looks like this project is not so actively maintained. Lots of old issues, more than half a year without commits. @tgjones, Is it alive?

@vladen what do you think?

**Comment by tgjones** [comment]
@quozd Almost all of the open issues are actually features. There's only one actual bug, which I haven't yet been able to resolve, but fortunately it doesn't affect many people.

There's little activity because the project is stable now - it's been around for a few years, and is currently on v3.1.1.

**Comment by quozd** [comment]
@tgjones thanks for clarification. Merged

**Comment by tgjones** [comment]
Great, thanks!

**Comment by vladen** [comment]
Cool stuff, with no doubts!

**Pull request merged**
