### PR TITLE
Added MyGet

### PR DESCRIPTION
**Pull request by xavierdecoster**
cc @MyGet

### CODE REVIEW

**Comment by quozd** [comment]
Hi @xavierdecoster , thank you for your contribution.

@vladen what do you think about this project? It's free for OSS, but I don't want to make our list full of ads.

**Comment by vladen** [comment]
Hmm. Good question. There was a proposal to split into two streams, one for OSS and another for awesome but proprietary or partially/fully commercial solutions. From the awesomeness perspective we should enlist as much as possible software that can be really useful. Does commercial nature of a product break its awesomeness? What about those developers who are ready to pay for cool and useful instrument? Imho, Teamcity is great and have to be known. The same for myget. Not so far ago I've got a question about free private NuGet repo, where to get it. Here is the answer.

**Comment by vladen** [comment]
It was wrong button )

**Comment by ghuntley** [comment]
Just because a product costs money does not mean that it is not awesome.
Developers should be prepared to pay for tools that provide value. Having a
commercial ecosystem is one of the indicators that companies use to gauge
maturity level.

**Comment by quozd** [comment]
I'm not saying that commercial software is not awesome. I just want to keep this list free from advertisements. 

To add any proprietary software we should define some strict guidelines which should help up decide whether some software can be added or not.  If we start adding proprietary projects based on our own opinion and feelings then guys will start asking me "why this one is in the list, but my project was rejected".

**Comment by vladen** [comment]
I think at least another list should be allocated for ads-like, proprietary or dual licensed software to keep clean the current one. Imho the main criteria for inclusion - usufulness for community. Other applicable criterias are maturity, stability, high value and perhaps presence of special licensing schema for open-source projects. Let's brainstorm this onwards.

**Comment by quozd** [comment]
@xavierdecoster  I've added contribution guidelines for a proprietary software. Please, change your PR to comply with these requirements before we can merge it.

**Comment by xavierdecoster** [comment]
Just added the Free-For-OSS tag. Note that MyGet has a Freemium model so anyone can join the Free offering. Those requesting the OSS plan get an extra special offering.

**Comment by quozd** [comment]
@xavierdecoster MyGet link should hav both [$] and [Free for OSS] tags. Please, fix. Then i will merge

**Comment by xavierdecoster** [comment]
Added. Thanks!

**Comment by quozd** [comment]
:+1:

**Pull request merged**
