### PR TITLE
Add RazorMailer

### PR DESCRIPTION
**Pull request by jonleigh**
Mail/RazorMailer - [https://github.com/jonleigh/RazorMailer](https://github.com/jonleigh/RazorMailer)

RazorMailer is a lightweight wrapper of [RazorEngine](https://github.com/Antaris/RazorEngine) that makes it simple to send Razor based emails from most .NET platforms, be is ASP.NET MVC / Web API, NancyFx, Hangfire, Console apps etc.

It's based on the latest version of RazorEngine, has fairly good documentation and although quite new, is actively maintained.

### CODE REVIEW

**Comment by pleb** [comment]
Maybe too new. Community to decide

**Comment by jonleigh** [comment]
Thanks for taking the time to review my pull request.  

I take your point about this project possibly being too new.  However, to the best of my knowledge (and for some unknown reason), all of the other libraries that allow Razor based emails to be sent are either a) suffering from bit rot or b) limited to ASP.NET MVC only.

This project solves both of those issues and is being actively used in production at my current company, [Moneybox](https://www.moneyboxapp.com).

**Comment by zihotki** [comment]
IMO, RazorEngine should be on the awesome list but this lib is just a small wrapper around RazorEngine. There are a plenty of such projects which are based on the same RazorEngine, I personally don't see any awesomeness.

**Comment by pleb** [comment]
@jonleigh 

Sorry, I'm going to close this one.

It's a good little wrapper library, and I'm sure if somebody searches for Razor and Mail they will find it.  However is it Awesome? The answer is probably no.

**Pull request closed without merging**
