### PR TITLE
Add Topaz OSS Authz

### PR DESCRIPTION
**Pull request by noashavit**
Add Topaz open-source authorization system for dotnet applications to the list. Please LMK if you need anything else. Thanks!

Authentication and Authorization - [Topaz](https://www.topaz.sh)

PROJECT_DESCRIPTION
Topaz is a standalone open-source authorization project for dotnet applications. You can deploy it in your cloud today to add RBAC, ABAC, or ReBAC, to your applications.

### CODE REVIEW

**Comment by Jogai** [comment]
This is a Go project...

**Comment by noashavit** [comment]
Yeah there is a robust dotnet sdk. The project is go-native, but we built a complete set of sdks so that it can be used on any app, regardless of frontend or backend language.

**Comment by Jogai** [comment]
Maybe the description should mention that or the link should go to the sdk then, but as its stands its really an outlier in the 'Authentication and Authorization' section.

**Comment by pleb** [comment]
Reverted. See #1171 for reasons

**Pull request merged**
