### PR TITLE
Add Reflex Trainer to Game category

### PR DESCRIPTION
**Pull request by StraykerPL**
Game/Reflex Trainer - [PROJECT_LINK](https://github.com/StraykerPL/reflex_trainer)

C# app to train point reflex!

### CODE REVIEW

**Comment by Jogai** [comment]
Why is this awesome? And why is this specific to dotnet?

**Comment by StraykerPL** [comment]
For me it's awesome. It's my app and I'm proud of it. I just wanted to show it to someone. It's written in C#, so it's based on .NET, just it.

**Comment by kiquenet** [comment]
It's not a  .NET libraries, tools or frameworks.
Sorry, for me not awesome software, only has a one form. NOt learned anything about patterns and practices.

**Comment by Jogai** [comment]
> For me it's awesome. It's my app and I'm proud of it. I just wanted to show it to someone. It's written in C#, so it's based on .NET, just it.

I see, but this list is not for showcasing, I think social media is better suited for that. For example https://www.reddit.com/r/creators/

**Comment by StraykerPL** [comment]
Ok, I understand. I will not add it here. Thank you for discussion, it will help me in my developer's work

**Pull request closed without merging**
