### PR TITLE
Add PDF version of Awesome .NET 

### PR DESCRIPTION
**Pull request by xsoheilalizadeh**
I've added PDF version.

### CODE REVIEW

**Comment by zihotki** [comment]
Hey, Thank you for your PR, having a PDF version may be helpful. But what scares me is that it's manually generated and somebody need to maintain it. It'll be out of sync very quickly.

**Comment by devSoheilAlizadeh** [comment]
@zihotki It's ok, I maintain it for till I prepare a process to make it automatically.

**Comment by zihotki** [comment]
> @zihotki It's ok, I maintain it for till I prepare a process to make it automatically.

That's great but I still would like to discuss the need of the PDF first. It never occured to me that people will need PDF of the list and I wonder what's the purpose and what problem they're trying to solve.

By the way, the issue you linked #738 is about adding, I think, EasyPdf wrapper component https://github.com/aleGuardiola/EasyPdf . It wasn't a request to create a PDF version.

**Comment by pleb** [comment]
Sorry @xsoheilalizadeh,

This entry isn't going to make the list.

Don't let this setback cause you to lose heart, and we look forward to your next contribution.

Thanks, Pleb

**Pull request closed without merging**
