### PR TITLE
Add Weekly C# Digest

### PR DESCRIPTION
**Pull request by jakubgarfield**
Newsletters/Weekly C# Digest - [Weekly C# Digest](http://csharpdigest.net/)

Weekly email newsletter with manually curated top 5 links from the .NET community.

### CODE REVIEW

**Comment by pleb** [comment]
I like it, but I don't know if it fits with "A collection of awesome .NET libraries, tools, frameworks, and software.". 

Let's wait a little and see what other members of the community think

**Comment by jakubgarfield** [comment]
[awesome-ruby](https://github.com/markets/awesome-ruby#resources) has a resource section, so would something like that work?

**Comment by alexkuznetsov** [comment]
vote for inclusion in the list, in "Resources" section, for example.

**Comment by YaroslavSchubert** [comment]
Vote for "Resources" section

**Comment by pleb** [comment]
Ok `Resources` have it. @jakubgarfield if you could update the PR to reflect this, I'll happily merge it ;)

**Comment by jakubgarfield** [comment]
thanks @pleb, I amended the previous commit to keep the git log tidy.

**Pull request merged**
