### PR TITLE
Added Empty Keys UI

### PR DESCRIPTION
**Pull request by EmptyKeys**
GUI/Empty Keys UI - [http://emptykeys.com/ui_library](http://emptykeys.com/ui_library)

Empty Keys UI is multi-platform engine agnostic XAML based user interface library. Comes with custom XAML to C# generator (open source) and multiple engine implementations (MonoGame, FNA, Xenko, SunBurn, CocosSharp).

### CODE REVIEW

**Comment by devkhan** [comment]
How mature is this library? (Age, community strength, StackOverflow questions, etc.)

**Comment by EmptyKeys** [comment]
Library is about 2 and half years old, version 2.2 at this moment with over 7000 downloads on NuGet https://www.nuget.org/profiles/EmptyKeys. There is about 590 users on forums, 157 topics.

Part of the library is open source - https://github.com/EmptyKeys/UI_Generator and https://github.com/EmptyKeys/UI_Engines

**Comment by devkhan** [comment]
That's nice. Can you rebase your branch so that there are not issues.

**Comment by EmptyKeys** [comment]
OK now? :)

**Comment by devkhan** [comment]
Thanks. 👍

**Pull request merged**
