### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by patricksadowski**
Some links are broken and a link to license is missing.

### CODE REVIEW

**Comment by zihotki** [comment]
The links has been fixed in PR #492 . As for the license for sure we need to make it more visible and probably think about moving it somewhere to the top, for that I created a separate issue #494 to discuss the details so I'm closing this PR.

**Comment by patricksadowski** [comment]
This is PR #492... Did you mean another PR?

**Comment by VPashkov** [comment]
This PR also removes broken link \[Other Awesome Lists](#other-awesome-lists)
Which was the right thing to do.
PR #492 didn't do that. And now this change is lost.
May be it possible to reopen this PR and merge it somehow?

**Comment by patricksadowski** [comment]
I've updated my branch to remove the broken link [Other Awesome Lists](#other-awesome-lists).

**Pull request closed without merging**
