### PR TITLE
Add Managed Windows API

### PR DESCRIPTION
**Pull request by hgupta9**
UI Automation/Managed Windows API - [sourceforge](http://mwinapi.sourceforge.net/)

Introspect and automate third-party Windows / VC++ applications by controlling the UI elements of the app.

### CODE REVIEW

**Comment by pleb** [comment]
@hgupta9 I'll leave this for the community. I couldn't find any unit tests, but because it's a niche product I think it could be overlooked

**Comment by hgupta9** [comment]
Its very reliable and I have made some additions too. Perhaps I'll upload it sometime.

**Comment by pleb** [comment]
@hgupta9 

If you have a version with additions, my guess is the SourceForge version is abandon ware?

Did you make to make GH repo for it and repath the link? The reason I ask is so that people submit issues and PRs etc. Thoughts?

**Comment by SlowLogicBoy** [comment]
I would love to have this linked somewhere, maybe it's not really suited here, but is there another .net list that would allow this to be added? If so we can add it there otherwise maybe we could have some section like untrusted/obsolete (but this would defeat the purpose of this list I guess). 
Anyway thanks @hgupta9 for posting this, I always Pinvoked Native/Unamanaged Windows API, I guess I will no more.

**Comment by zihotki** [comment]
It's a very niche but when you need to work with Windows API it's really awesome

**Comment by hgupta9** [comment]
@pleb Should I create a GH repo for this since its abandoned by the original author? I could upload my additions too?

**Pull request merged**
