### PR TITLE
Added Wave engine

### PR DESCRIPTION
**Pull request by Jogai**
WAVE ENGINE, the ultimate solution that enables you, game developer, to focus in creating mobile games using one of the leading programming language C#.

I looked at the requirements for proprietary and commercial projects:

* Wave has a forum and a subreddit
* Version 1.4 was released more than a year ago, now on version 2
* Free, but you have to include the wave logo on the splash screen of your game.

### CODE REVIEW

**Comment by Jeffiy** [comment]
cc @quozd

**Comment by quozd** [comment]
@Jogai please, add **[Free]** tag and we'll merge it

**Comment by Jogai** [comment]
Àdded & squashed

**Comment by Jeffiy** [comment]
Thanks.

**Pull request merged**
